name: Swift Integration Tests

on:
  workflow_dispatch:
    branches:
  pull_request:
    branches:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    name: Tests
    runs-on: self-hosted
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=15.4,name=iPhone 13 Pro']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build and Test
        uses: sersoft-gmbh/xcodebuild-action@v1
        with: 
          project: FantasmoSDK.xcodeproj
          scheme: FantasmoSDKTests
          destination: ${{ matrix.destination }}
          action: test
